### ISSUE TITLE
clustering result issue

### ISSUE THREAD

**Issue by wangjiusi** [bnpy/bnpy#13]
Hi, I have encountered some problems with clustering results when I want to cluster some image data sets. I would be very grateful if you could give me some advice.

My problem is described below:
      My data set come from [http://cvcl.mit.edu/database.htm](url) . It contains 8 data categories. I first use the SIFT algorithm to extract features from each image, then reduce each feature vector to 50, 100, 150, 200 dimensions through PCA, and finally use the resulting feature data as input to bnpy. But the clustering results are only one or two. Then I tried the Iris flower dataset and got similar results. So I thought if the data set is too small since the data set in your paper is large or my preprocessing is not appropriate.

      the code is:
      `alg = cv2.xfeatures2d.SIFT_create()
        kps = alg.detect(image)
        kps, dsc = alg.compute(image, kps)
        dsc = dsc.flatten()`

        `K1_trained_model, K1_info_dict = bnpy.run(
    dataset, 'DPMixtureModel', 'Gauss', 'memoVB',
    output_path='/tmp/AsteriskK8/trymoves-K=1/',
    nLap=100, nTask=1, nBatch=2,
    sF=0.1, ECovMat='eye',
    K=3, initname='randexamples',
    moves='birth,merge,shuffle',
    m_startLap=30, b_startLap=2, b_Kfresh=4)`

**Comment by michaelchughes** [comment]
If you were to share the iris dataset code you are using, that might be the most helpful, since we could reproduce it end-to-end easily.

Broadly, remember that DP mixture models in general are *not* supervised algorithms. They will not necessarily find exactly a set of categories that might be known for the data. Instead, they'll find the best Gaussian mixture model fit to the data (maximizing marginal likelihood). It's only if a single Gaussian fits each category's data well that the learned clusters will match the known clusters.

If you are not satisfied with the number of clusters found, I recommend:
* increasing the DPMixtureModel concentration parameter (\gamma)
* playing with the Gaussian observation model's hyperparameters ([docs](https://bnpy.readthedocs.io/en/latest/obsmodel/DiagGaussObsModel-VB.html))
* initializing the optimization algorithm with more clusters (set K = 10 or K=50), not K=3
* using a better init scheme than 'randexamples'. See ["Initialization for Mixtures of Gaussians"](https://bnpy.readthedocs.io/en/latest/examples/01_asterisk_K8/plot-01-demo=init_methods-model=mix+gauss.html#sphx-glr-examples-01-asterisk-k8-plot-01-demo-init-methods-model-mix-gauss-py) for some alternatives
* trying more aggressive birth move steps (tweak --b_Kfresh and other --b_???? flags). See [moves.conf](https://github.com/bnpy/bnpy/blob/master/bnpy/config/moves.conf)

In a perfect world, our birth/merge moves would take care of all this. Alas, these moves cannot always overcome the current local optima.

**Comment by wangjiusi** [comment]
@michaelchughes 

thank you for your reply！
Based on your suggestion, I try to adjust some a prior information to get better results. But I failed.
I am trying to cluster [CIFAR-10 dataset](https://www.cs.toronto.edu/~kriz/cifar.html) using memeVB as the experiment of your paper. The CIFAR-10 dataset consists of 60000 32x32 color images in 10 classes, with 6000 images per class. The full code address is [here](https://github.com/wangjiusi/clustering/blob/master/cluster.ipynb)

**Comment by wangjiusi** [comment]
Thanks!

I solved the problem by constantly adjusting the parameters and feature extraction methods.
